[paleta]
cor_fundo = "#EEEEEE"
cor_seletor_radial = "#C0C0C0"
cor_hover = "##00BFFF"
cor_grade = "#A9A9A9"
cor_borda_grade = "#000000"
cor_barra_lateral = "#000000"
cor_barra_superior = "#878787"
cor_entidade = "#EEEEEE"
cor_borda_entidade = "#000000"