name: Build

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build-project:
    name: Build-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Create jar file
        run: ./gradlew jar
      - name: Print program version
        run: java -jar ./build/libs/der-modelador.jar --version

