on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/der-modelador.jar"
        bodyFile: "release_body.md" 
        makeLatest: true
